// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbBy8D5bx0L6-IFBxrkmd5gxKVeXNVESk',
    appId: '1:187465575370:web:d99b6e8a2306fa49e93d33',
    messagingSenderId: '187465575370',
    projectId: 'globalhealth-b6123',
    authDomain: 'globalhealth-b6123.firebaseapp.com',
    databaseURL: 'https://globalhealth-b6123-default-rtdb.firebaseio.com',
    storageBucket: 'globalhealth-b6123.firebasestorage.app',
    measurementId: 'G-8LNMQGR8RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgdTQq2jwwSO3cw4VWoUahj-BJ8LLwV7w',
    appId: '1:187465575370:android:eb34493292f383b3e93d33',
    messagingSenderId: '187465575370',
    projectId: 'globalhealth-b6123',
    databaseURL: 'https://globalhealth-b6123-default-rtdb.firebaseio.com',
    storageBucket: 'globalhealth-b6123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAic5i3fDll8Wtv7nH6tUxJZvFwI1E37WM',
    appId: '1:187465575370:ios:50ab3b221b0cda73e93d33',
    messagingSenderId: '187465575370',
    projectId: 'globalhealth-b6123',
    databaseURL: 'https://globalhealth-b6123-default-rtdb.firebaseio.com',
    storageBucket: 'globalhealth-b6123.firebasestorage.app',
    androidClientId: '187465575370-u3hoqgpb7p5oh4linp0aei48si9uer41.apps.googleusercontent.com',
    iosClientId: '187465575370-s3fhj813amri655h8sj2fvb6qbgavlja.apps.googleusercontent.com',
    iosBundleId: 'com.example.globalHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAic5i3fDll8Wtv7nH6tUxJZvFwI1E37WM',
    appId: '1:187465575370:ios:50ab3b221b0cda73e93d33',
    messagingSenderId: '187465575370',
    projectId: 'globalhealth-b6123',
    databaseURL: 'https://globalhealth-b6123-default-rtdb.firebaseio.com',
    storageBucket: 'globalhealth-b6123.firebasestorage.app',
    androidClientId: '187465575370-u3hoqgpb7p5oh4linp0aei48si9uer41.apps.googleusercontent.com',
    iosClientId: '187465575370-s3fhj813amri655h8sj2fvb6qbgavlja.apps.googleusercontent.com',
    iosBundleId: 'com.example.globalHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbBy8D5bx0L6-IFBxrkmd5gxKVeXNVESk',
    appId: '1:187465575370:web:298996e6a22b4d6be93d33',
    messagingSenderId: '187465575370',
    projectId: 'globalhealth-b6123',
    authDomain: 'globalhealth-b6123.firebaseapp.com',
    databaseURL: 'https://globalhealth-b6123-default-rtdb.firebaseio.com',
    storageBucket: 'globalhealth-b6123.firebasestorage.app',
    measurementId: 'G-XRH288ZR94',
  );

}